name: Build and Deploy Docker Image

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}/one-node-pdf:latest

jobs:
  build:
    runs-on: ubuntu-22.04  # Menentukan runner Ubuntu 22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.20.4'  # Menggunakan versi Node.js 18.20.4

      - name: Install dependencies
        run: yarn install

      - name: Build application
        run: yarn run build

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME .
          docker inspect $IMAGE_NAME || exit 1

      - name: Verify Docker image
        run: docker images | grep one-node-pdf

  deploy:
    runs-on: ubuntu-22.04  # Menentukan runner Ubuntu 22.04
    needs: build  # Menjalankan job ini setelah job build selesai

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME
