name: Dev CI/CD Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.20.4'

      - name: Install dependencies
        run: yarn install

      - name: Build application
        run: yarn run build

  deploy:
    name: Deploy Docker Image
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GIT_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build \
            --file Dockerfile \
            --tag ghcr.io/${{ github.repository }}/one-node-pdf:latest .

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}/one-node-pdf:latest
