name: Build and Push to GHCR

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build_and_push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # Checkout code repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Authenticate with GCP
      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

      # Configure Google Cloud Project
      - name: Configure gcloud
        run: gcloud config set project <GCP_PROJECT>
  
      # Retrieve .env file from Google Secret Manager
      - name: Retrieve .env file from Secret Manager
        run: |
          # Ambil file dari Secret Manager
          gcloud secrets versions access latest --secret=ONE_NODE_PDF > .env
          # Export semua variabel di .env ke $GITHUB_ENV
          set -a
          source .env
          set +a
  
      # Debugging: Print environment variables (optional)
      - name: Print environment variables (optional debugging)
        run: env

      # Login to GitHub Container Registry
      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      # Build and push Docker image
      - name: Build and Push Docker image
        run: |
          docker buildx build \
            --push \
            --file Dockerfile \
            --tag ghcr.io/${{ github.repository }}/one-node-pdf:latest 
