name: Dev CI/CD Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build_and_push: # Perubahan nama job untuk konsistensi
    name: Build image & push
    runs-on: ubuntu-latest

    # Tambahkan permissions untuk mengatur hak akses
    permissions:
      contents: read        # Membaca konten repository
      packages: write       # Menulis paket ke GitHub Container Registry

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build \
            --file deploy/Dockerfile.app \
            --tag ghcr.io/${{ github.repository }}/one-node-pdf:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/one-node-pdf:latest
