name: Build and Push to GHCR

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build_and_push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Gcp setup
      - name: Set up GCP Service Account
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}   

      # Set up environment
      - name: Set up environment
        run: |
          gcloud secrets versions access latest --secret="ONE_NODE_PDF" > .env
          export $(cat .env | xargs)

      # Login to GitHub Container Registry
      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      # Build and Push Docker image
      - name: Build and Push Docker image
        run: |
          docker buildx build \
            --push \
            --file Dockerfile \
            --tag ghcr.io/${{ github.repository }}/one-node-pdf:latest \
            --tag ghcr.io/${{ github.repository }}/one-node-pdf:${{ github.sha }} .
