name: Dev CI/CD Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        run: |
          set -e
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build Docker image
        run: |
          set -e
          docker build \
            --file deploy/Dockerfile.app \
            --tag ghcr.io/${{ github.repository }}/one-node-pdf:latest .

      - name: Push Docker image
        run: |
          set -e
          docker push ghcr.io/${{ github.repository }}/one-node-pdf:latest
