name: Dev CI/CD Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build-requirement:
    runs-on: ubuntu-22.04 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.20.4'

      - name: Install dependencies
        run: yarn install

      - name: Build application
        run: yarn run build

  deploy-to-ghcr:
    runs-on: ubuntu-22.04 
    needs: build-requirement 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.20.4'

      - name: Build Docker image
        run: docker build -t ghcr.io/one-d-plate/one-node-pdf/one-node-pdf:latest .

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Push Docker image
        run: docker push ghcr.io/one-d-plate/one-node-pdf/one-node-pdf:latest
